# Generated by Django 6.0.4 on 2026-05-05 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_create_settings_rows(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    UserSettings = apps.get_model("accounts", "UserSettings")
    for user in User.objects.all().iterator():
        UserSettings.objects.get_or_create(user=user)


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional name shown in the app (no separate username field).', max_length=150, verbose_name='display name'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=16)),
                ('language', models.CharField(default='en', max_length=16)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user settings',
                'verbose_name_plural': 'user settings',
            },
        ),
        migrations.RunPython(forwards_create_settings_rows, backwards_noop),
    ]
